swagger: '2.0'
info:
  title: "API Documentation"
  description: "API Documentation"
  version: "0.0.0"

host: "localhost:9000"
schemes: [ "http" ]
basePath: "/"
produces: [ "application/json" ]
consumes: [ "application/json" ]

paths:
  /register:
    post:
      summary: "Completes a registration"
      description: "Must have a valid session after Reddit OAuth"
      responses:
        201:
          description: "Account was created"
        400:
          description: "Invalid data in request"
      parameters:
        - name: request
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/RegisterRequest"

definitions:
  RegisterRequest:
    type: "object"
    required: ["email", "password", "confirm"]
    properties:
      email:
        type: "string"
      password:
        type: "string"
      confirm:
        type: "string"
    example:
      email: "example@example.com"
      password: "hunter2"
      confirm: "hunter2"