-- setup uuid extension first
CREATE SCHEMA IF NOT EXISTS "uuid";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA uuid;

CREATE TABLE IF NOT EXISTS "Users" (
  id BIGSERIAL NOT NULL CONSTRAINT "PK_Users" PRIMARY KEY,
  username TEXT NOT NULL CONSTRAINT "UQ_Users_username" UNIQUE,
  email TEXT NOT NULL,
  created TIMESTAMPTZ NOT NULL
);